/**
 * @fileName TerminalFactory.java
 * @author Xingzi Guo (xingzig@andrew.cmu.edu)
 * @Andrew ID: xingzig
 * @Assignment: Homework 9-1 genetic programming
 * @date Last Modified: 11/17/2014
 * @description: In this assignment, we will generate 500 GPTrees and evolve 5 generation of trees.  
 * @description: TerminalFactory is used to give out random terminals
 */
/* Generated by Together */
import java.util.*;

/** Produces a terminal Node (either a Variable or a Const). */

public class TerminalFactory {
    private int numIndepVars;
    /** Sets the range of X-variables that this factory can supply.
    * @param n The number of independent variables. */
    TerminalFactory(int n) { numIndepVars = n; }
    /** Returns a randomly selected Variable or Const. The selection is uniform
    * over the range [X0, X1,...Xn, Const] */
    public Node getTerminal(Random rand) {
        Node n = null;
        int i = rand.nextInt(numIndepVars + 1);
        if (i < numIndepVars)
            n = new Variable(i);
        else
            n = new Const(rand.nextDouble());
        return n;
    }
    public int getNumIndepVars() { return numIndepVars; }
}
